
package com.govindtank.unlockcount


const val DAY_END_MS_PREFERENCE = "DAY_END_MS_PREFERENCE"

const val COUNT_PREFERENCE = "COUNT_PREFERENCE"

const val COUNT_PREFERENCE_DEFAULT_VALUE = 0

const val PREVIEW_COUNT = 1

const val PREV_COUNT_PREFERENCE = "PREV_COUNT_PREFERENCE"

const val PREV_COUNT_PREFERENCE_DEFAULT_VALUE = 0